import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(readFileSync(join(root, 'release.json'), 'utf8'));
const out = join(root, 'dist');
mkdirSync(join(out, 'fonts'), { recursive: true });
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
for (const [key, host] of [['appStoreUrl', 'apps.apple.com'], ['playStoreUrl', 'play.google.com']]) {
  if (config[key] && (new URL(config[key]).protocol !== 'https:' || new URL(config[key]).hostname !== host)) throw Error(`Invalid ${key}`);
}
for (const file of ['styles.css', 'mark.svg', 'delete-account.js']) copyFileSync(join(root, file), join(out, file));
for (const [folder, file, target] of [
  ['instrument-serif', '400Regular/InstrumentSerif_400Regular.ttf', 'InstrumentSerif-Regular.ttf'],
  ['inter', '400Regular/Inter_400Regular.ttf', 'Inter-Regular.ttf'],
]) copyFileSync(join(root, '../app/node_modules/@expo-google-fonts', folder, file), join(out, 'fonts', target));

for (const family of ['inter', 'instrument-serif']) copyFileSync(join(root, '../app/node_modules/@expo-google-fonts', family, 'LICENSE_FONT'), join(out, 'fonts', `${family}-LICENSE.txt`));

const preview = !config.privacyApproved || !config.operatorName || !config.supportEmail;
const notice = preview ? '<aside class="notice"><strong>Prelaunch preview.</strong> Mirra is not yet available in the stores. These policies describe the current implementation; operator and private-support details must be finalized before public release.</aside>' : '';
const downloads = `${config.appStoreUrl ? `<a class="button" href="${esc(config.appStoreUrl)}">Download for iPhone ↗</a>` : '<span class="button secondary" aria-disabled="true">iPhone · coming soon</span>'}
  ${config.playStoreUrl ? `<a class="button secondary" href="${esc(config.playStoreUrl)}">Get it for Android ↗</a>` : '<span class="button secondary" aria-disabled="true">Android · coming later</span>'}`;
const support = config.supportEmail ? `<a href="mailto:${esc(config.supportEmail)}">${esc(config.supportEmail)}</a>` : 'Private support contact is being finalized before launch. Do not post recordings, transcripts, passwords, or personal information on public issue trackers.';
function page(file, title, description, content, document = false) {
  const canonical = `${config.siteUrl}/${file === 'index.html' ? '' : file}`;
  writeFileSync(join(out, file), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="canonical" href="${esc(canonical)}"><link rel="icon" href="./mark.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css">${preview ? '<meta name="robots" content="noindex">' : ''}</head><body><a class="skip" href="#main">Skip to content</a><div class="wrap"><header><a class="brand" href="./"><img src="./mark.svg" alt="" width="30" height="30">mirra</a><nav aria-label="Main"><a href="./#how-it-works">How it works</a><a href="./privacy.html">Privacy</a><a href="./support.html">Support</a></nav></header><main id="main" ${document ? 'class="document"' : ''}>${content}</main><footer><span>Mirra · A little more room for connection.</span><div><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a><a href="./support.html">Support</a><a href="./delete-account.html">Delete account</a></div></footer></div></body></html>`);
}
page('index.html', 'Mirra — make room for better conversations', 'Record with permission. Notice your conversational habits. Try one small change next time.', `
<section class="hero"><div><p class="eyebrow">Conversation coaching, at your pace</p><h1>A little less talking.<br>A little more <em>connection.</em></h1><p class="intro">The best conversations leave room for both of you. Mirra helps you notice how you listen, ask, and respond — then find one small thing to try next time.</p><div class="actions">${downloads}</div><p class="note">For adults 18+. iPhone release in preparation.</p></div>
<div class="phone-stage"><div class="phone" aria-label="Illustrative conversation debrief"><div class="phone-top"><span>9:41</span><span>● ● ●</span></div><p class="tiny">A moment to reflect</p><h3>A conversation<br>worth noticing.</h3><p class="tiny">Illustrative example · 12 min</p><div class="reflection"><p class="eyebrow">One thing to try</p><p>Let the pause do<br>a little more work.</p><span class="note">Before your next question, leave a breath.</span></div><div class="metric"><span class="tiny">Talk / listen</span><strong>48 / 52</strong></div><div class="metric"><span class="tiny">Questions asked</span><strong>6</strong></div><div class="metric"><span class="tiny">Room for reflection</span><div class="mini-bars">${[12,22,30,16,25,14,32,20,12].map(h => `<i style="height:${h}px"></i>`).join('')}</div></div><p class="note">Estimates, never a judgment.</p></div><span class="example-label">ILLUSTRATIVE EXAMPLE · NOT A USER RECORDING</span></div></section>
<section class="section" id="how-it-works"><div class="section-head"><div><p class="eyebrow">A small practice</p><h2>Notice. Reflect.<br><em>Try again.</em></h2></div><p>No score to chase. Just a clearer view of your habits and a practical next step.</p></div><div class="steps"><article><div class="step-number">01 / Make space</div><h3>Ask, then record.</h3><p>Get everyone's permission before recording or importing audio. Stop and save when you're done; an offline recording waits on your device for a connection.</p></article><article><div class="step-number">02 / Look back</div><h3>Find the pattern.</h3><p>Review estimated speaking time, questions, interruptions, and other signals alongside a short AI debrief.</p></article><article><div class="step-number">03 / Move forward</div><h3>Take one small step.</h3><p>Explore a moment in Reflect, choose something to practice, and return to your conversations over time.</p></article></div></section>
<section class="section"><div class="privacy-block"><div><p class="eyebrow">Care comes first</p><h2>Your conversations<br>deserve <em>care.</em></h2><a href="./privacy.html">Read how your data is handled ↗</a></div><div><p>Mirra uses OpenAI for transcription and coaching, and Supabase for your account and saved debriefs. You choose whether to save transcripts.</p><ul><li>Explicit permission before AI processing.</li><li>Delete a conversation or your whole account.</li><li>Export your saved data.</li><li>No ads or advertising trackers in the app.</li></ul><p class="note">AI and speaker estimates can be wrong. Mirra is a reflection tool, not medical or mental-health care.</p></div></div></section>
<section class="download" id="download"><p class="eyebrow">A little more presence</p><h2>Your next conversation<br>is a place to <em>begin.</em></h2><div class="actions">${downloads}</div><p class="note">Five debriefs per month. No paid plans in the first release.</p></section>`);

page('privacy.html', 'Privacy Policy — Mirra', 'What Mirra collects, how AI processing works, and how to access or delete your data.', `<p class="eyebrow">Your data, explained</p><h1>Privacy Policy</h1><p class="muted">Version September 14, 2026</p>${notice}
<h2>Who is responsible</h2><p>${config.operatorName ? esc(config.operatorName) : 'The service operator is not yet confirmed for public launch.'} Contact: ${support}</p>
<h2>What the app processes</h2><table><thead><tr><th>Data</th><th>Purpose and storage</th></tr></thead><tbody><tr><td>Account details</td><td>Email, account ID, authentication credentials or provider identifiers, and preferences are managed by Supabase Auth and our database.</td></tr><tr><td>Recordings</td><td>Your device saves stopped recordings until a successful upload or explicit discard. Our backend temporarily decodes the audio and sends it to OpenAI for transcription; we do not keep an audio archive on our backend.</td></tr><tr><td>Transcripts and debriefs</td><td>OpenAI receives the labeled conversation and derived statistics for coaching. Debriefs and statistics are saved to your account. Transcript storage is off for new users unless you enable it. Existing saved transcripts are not erased simply by switching this preference off.</td></tr><tr><td>Reflect messages</td><td>Messages, recent chat context, and relevant debriefs go to OpenAI. Saved transcript excerpts are included only when you enable that setting. Reflect chat history stays in the current app session and is not saved by Mirra as a separate chat archive.</td></tr><tr><td>Operational records</td><td>Hosting and authentication providers may process IP addresses, request timestamps and security logs. Monthly usage counters enforce the debrief limit. We do not intentionally log audio, transcript text or chat prompts.</td></tr></tbody></table>
<h2>AI and service providers</h2><p>OpenAI provides transcription and AI coaching. Supabase provides authentication and database storage. Requests for text coaching use <code>store=false</code>; this does not eliminate all provider retention. OpenAI's API data controls describe endpoint-specific handling and possible abuse-monitoring retention, generally up to 30 days for text requests unless an exception applies. API content is not used to train OpenAI models by default. See <a href="https://developers.openai.com/api/docs/guides/your-data">OpenAI's data controls</a> and <a href="https://supabase.com/privacy">Supabase's privacy policy</a>.</p>
<h2>Permission and choices</h2><p>You explicitly agree before AI processing. Record only after everyone involved permits both recording and processing. Recording rules depend on location and circumstances; permission from you alone may not be sufficient. Do not upload sensitive conversations you do not have permission to share.</p><p>You can withdraw AI consent from Profile. This stops future processing; it cannot recall a request already sent. Saved conversations remain available for viewing, export, or deletion. Microphone access can be revoked in device settings. The app does not use location, contact lists, advertising IDs, advertising trackers, or health-record integrations.</p>
<h2>Retention and deletion</h2><p>Saved debriefs and optional transcripts remain until you delete them or your account. A content-free deletion marker remains until account deletion to prevent delayed uploads from restoring a deleted conversation. Delete a conversation from its detail screen. Delete your account from Profile → Account actions → Delete account. This removes the Supabase account and associated debriefs, usage and preferences; local queued recordings on that device are also removed. Other devices may retain offline files until their app data is removed; uninstall Mirra or clear its local storage on devices you no longer use.</p><p>Backups and providers' security or abuse-monitoring records may persist under their configured retention and legal obligations. Deletion from the live database does not promise immediate removal from every backup. The production backup schedule and hosting retention must be recorded before launch.</p>
<h2>Your rights and safety</h2><p>Depending on where you live, you may have rights to access, correct, export, restrict or delete personal data and to complain to your local data-protection authority. Use the in-app export and deletion controls or <a href="./delete-account.html">web deletion page</a>. Contact information and any applicable regional representative must be finalized before public release. Mirra is intended for adults 18 and over and is not designed for children.</p><p>Data may be processed outside your country by the named providers. Production regions, applicable transfer safeguards, and the operator's legal basis for processing must be reviewed before expanding release territories. We use authenticated requests and account-scoped access controls, but no system can promise absolute security.</p><h2>Changes</h2><p>Material changes to AI processing require a new consent version. The current version is displayed above.</p>`, true);

page('terms.html', 'Terms of Use — Mirra', 'Use Mirra responsibly, with permission and realistic expectations about AI coaching.', `<p class="eyebrow">Using Mirra responsibly</p><h1>Terms of Use</h1><p class="muted">Version September 14, 2026</p>${notice}
<h2>The service</h2><p>Mirra helps adults reflect on their conversational habits using recorded audio, estimated statistics, and AI-generated coaching. The first release offers up to five debriefs per account per calendar month and up to 60 Reflect messages per hour. Deleting a completed debrief does not restore usage. Processing, availability, and results may vary.</p>
<h2>Permission to record and process</h2><p>You must be 18 or older and have permission from everyone involved before recording or uploading a conversation for Mirra and OpenAI to process. Comply with the laws and rules that apply to the participants and location, including workplace and professional confidentiality. Do not secretly record people, impersonate them, upload unlawful content, or use Mirra for surveillance or harassment. Stop recording if permission is withdrawn.</p>
<h2>Your content and account</h2><p>You retain rights in your content. You give the service only the permission needed to process it, provide your debriefs, and operate the features you choose. Keep sign-in links and credentials private. Use a verified email you control. Do not attempt to access another person's data, circumvent usage limits, or interfere with the service. You may export your saved data or delete your account at any time through the available controls.</p>
<h2>Understand the limits</h2><p>AI can invent details or misunderstand context. Speaker identification assumes the loudest speaker is the account holder and may be wrong. Acoustic and language measurements are estimates, not verified assessments of personality, emotions, health, relationships, honesty, or competence. Do not use them to make employment, educational, medical, legal or other consequential decisions about someone.</p><p>Mirra is not a clinician, therapist, diagnostic service, legal adviser, emergency service or substitute for professional care. It does not monitor conversations for emergencies. Seek appropriate professional or emergency help when needed.</p>
<h2>Availability and changes</h2><p>We cannot guarantee uninterrupted service or a particular outcome. Offline recordings upload only when the app is open with a working connection. Stopping and saving a recording before closing the app is necessary for recovery. Device loss, uninstalling, or clearing browser data may erase local recordings. Important changes to the service or these terms will be communicated through the app or published notices.</p>
<h2>Contact and applicable rights</h2><p>${support}</p><p>Nothing here excludes rights or remedies that cannot lawfully be excluded. The legal operator, release territories, governing-law provisions, dispute process, and any warranties or liability terms require final review before public launch. No arbitration agreement or broad waiver is imposed by this preview.</p><p><a href="./privacy.html">Read the Privacy Policy</a>.</p>`, true);

page('support.html', 'Support — Mirra', 'Help with recording, sign-in, privacy, account deletion, and conversation coaching.', `<p class="eyebrow">A little help</p><h1>Here when you need a hand.</h1>${notice}<div class="faq">
<details open><summary>How do I start?</summary><p>Sign in with your email link, review the AI disclosure, then ask everyone involved for permission. Keep the microphone near you. Tap Record, have your conversation, then tap Stop and keep Mirra open while it uploads.</p></details>
<details><summary>Where is my email link?</summary><p>Check spam and make sure you entered the right address. Use the newest link. Existing Google users can request a link to the same email address. Older username accounts can still use the username sign-in option.</p></details>
<details><summary>What happens without internet?</summary><p>After you have signed in and accepted processing, stopped recordings can wait safely on your device. Keep the app open after reconnecting to upload. The app cannot upload while force-quit. Avoid clearing app or browser data until your recordings have uploaded.</p></details>
<details><summary>Why is a recording waiting?</summary><p>Check connectivity, sign-in status, and your monthly usage. Oversized or unsupported recordings stay available to discard. Imports must be under 25 MB and no longer than 60 minutes. The app tells you when processing failed; it should not substitute an invented debrief.</p></details>
<details><summary>Do the charts know which speaker is me?</summary><p>No verified identity is available. Mirra estimates that the loudest speaker is you. Microphone placement, overlapping voices, noise and transcription mistakes can change results. Treat the debrief as a prompt for reflection, not a verdict.</p></details>
<details><summary>How do I delete my data?</summary><p>Open a conversation and tap Delete. For everything, open Profile → Account actions → Delete account. You can also <a href="./delete-account.html">use account deletion on the web</a>. Export first if you want a copy.</p></details>
<details><summary>Can I stop AI processing?</summary><p>Open Profile and withdraw AI processing consent. This pauses future recording uploads and Reflect requests. You can still export or delete saved data.</p></details></div>
<h2>Contact</h2><p>${support}</p><h2>Credits</h2><p>Mirra uses the Inter and Instrument Serif typefaces under the SIL Open Font License. <a href="./fonts/inter-LICENSE.txt">Inter license</a> / <a href="./fonts/instrument-serif-LICENSE.txt">Instrument Serif license</a>. App dependency notices are available in Profile.</p><p>For non-private bug reports, use the <a href="https://github.com/jonathanj502/mirra/issues">Mirra issue tracker</a>. Describe what happened, your device and app version. Never post audio, transcripts, credentials, or another person's information there.</p>`, true);

page('delete-account.html', 'Delete your account — Mirra', 'Delete a Mirra account and its associated saved conversations without reinstalling the app.', `<p class="eyebrow">Your account, your choice</p><h1>Delete your account.</h1><p>This permanently removes your Mirra account, saved debriefs, transcripts, settings and monthly usage records. It cannot be undone. Export a copy in the app first if you want one. Locally queued recordings on other devices should be discarded there or removed by clearing the app's data.</p><p>The app also supports deletion from Profile → Account actions → Delete account.</p>
<div id="availability" class="notice">Checking availability…</div><form id="sign-in" class="form" hidden><label for="email">Email for your existing account</label><input id="email" name="email" type="email" autocomplete="email" required><button class="button" type="submit">Email a secure deletion sign-in link</button></form><section id="confirmed-account" hidden><p id="account-label"></p><button class="button" id="delete">Permanently delete my account</button></section><output id="result" aria-live="polite"></output><p class="note">Signing in does not delete anything. You must separately confirm deletion.</p><script src="./delete-account.js" defer></script>`, true);
writeFileSync(join(out, 'release.json'), JSON.stringify(config));
writeFileSync(join(out, '.nojekyll'), '');
writeFileSync(join(out, 'robots.txt'), `User-agent: *\n${preview ? 'Disallow: /' : 'Allow: /'}\n`);
console.log(`Built 5 pages in ${out}. Public launch approved: ${!preview}`);
