import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = dirname(fileURLToPath(import.meta.url));
const version = createHash('sha256').update(readFileSync(join(root, 'styles.css'))).update(readFileSync(join(root, 'delete-account.js'))).update(readFileSync(join(root, 'site.js'))).update(readFileSync(join(root, 'mark.svg'))).digest('hex').slice(0, 12);
const config = JSON.parse(readFileSync(join(root, 'release.json'), 'utf8'));
const out = join(root, 'dist');
mkdirSync(join(out, 'fonts'), { recursive: true });
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
for (const [key, host] of [['appStoreUrl', 'apps.apple.com'], ['playStoreUrl', 'play.google.com']]) {
  if (config[key] && (new URL(config[key]).protocol !== 'https:' || new URL(config[key]).hostname !== host)) throw Error(`Invalid ${key}`);
}
for (const file of ['styles.css', 'mark.svg', 'delete-account.js', 'site.js', 'conversation.webp', 'conversation-small.webp']) copyFileSync(join(root, file), join(out, file));
for (const [folder, file, target] of [
  ['instrument-serif', '400Regular/InstrumentSerif_400Regular.ttf', 'InstrumentSerif-Regular.ttf'],
  ['inter', '400Regular/Inter_400Regular.ttf', 'Inter-Regular.ttf'],
  ['inter', '500Medium/Inter_500Medium.ttf', 'Inter-Medium.ttf'],
  ['inter', '600SemiBold/Inter_600SemiBold.ttf', 'Inter-SemiBold.ttf'],
  ['instrument-serif', '400Regular_Italic/InstrumentSerif_400Regular_Italic.ttf', 'InstrumentSerif-Italic.ttf'],
]) copyFileSync(join(root, '../app/node_modules/@expo-google-fonts', folder, file), join(out, 'fonts', target));

for (const family of ['inter', 'instrument-serif']) copyFileSync(join(root, '../app/node_modules/@expo-google-fonts', family, 'LICENSE_FONT'), join(out, 'fonts', `${family}-LICENSE.txt`));

const preview = !config.privacyApproved || !config.operatorName || !config.supportEmail;
const notice = preview ? '<aside class="notice"><strong>Policy details pending.</strong> These pages describe the current implementation. Operator and private-support details are still being finalized.</aside>' : '';
const downloads = [
  config.appStoreUrl && `<a class="button" href="${esc(config.appStoreUrl)}">Download for iPhone ↗</a>`,
  config.playStoreUrl && `<a class="button secondary" href="${esc(config.playStoreUrl)}">Get it for Android ↗</a>`,
].filter(Boolean).join('');
const storeUrl = config.appStoreUrl || config.playStoreUrl;
const storeLabel = config.appStoreUrl ? 'Download for iPhone' : 'Get it for Android';
const iphoneAvailable = config.iphoneAvailable === true || Boolean(config.appStoreUrl);
const androidAvailable = config.androidAvailable === true || Boolean(config.playStoreUrl);
const availablePlatforms = [iphoneAvailable && 'iPhone', androidAvailable && 'Android'].filter(Boolean).join(' and ');
const launchStatus = availablePlatforms ? `Available for ${availablePlatforms}` : 'Coming first to iPhone';
const availability = availablePlatforms
  ? `Mirra is available for ${availablePlatforms}.${!androidAvailable ? ' Android is not available yet.' : ''}`
  : 'Mirra is preparing for its first iPhone release, with Android to follow. Store downloads are not available yet.';
const headerAction = storeUrl
  ? `<a class="header-cta" href="${esc(storeUrl)}">${storeLabel} <span aria-hidden="true">↗</span></a>`
  : `<span class="header-status">${launchStatus}</span>`;
const heroAction = storeUrl
  ? `<a class="button" href="${esc(storeUrl)}">${storeLabel} <span aria-hidden="true">↗</span></a>`
  : `<p class="launch-status"><span class="status-dot" aria-hidden="true"></span>${launchStatus}</p>`;
const support = config.supportEmail ? `<a href="mailto:${esc(config.supportEmail)}">${esc(config.supportEmail)}</a>` : 'Private support contact is being finalized. Do not post recordings, transcripts, passwords, or personal information on public issue trackers.';
const navigation = '<a href="./#your-goals">Your goals</a><a href="./#how-it-works">How it works</a><a href="./privacy.html">Privacy</a><a href="./support.html">Support</a>';
function page(file, title, description, content, document = false) {
  const canonical = `${config.siteUrl}/${file === 'index.html' ? '' : file}`;
  writeFileSync(join(out, file), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="theme-color" content="#fcfaf4"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Mirra"><meta property="og:url" content="${esc(canonical)}"><link rel="canonical" href="${esc(canonical)}"><link rel="icon" href="./mark.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css?v=${version}"><script src="./site.js?v=${version}" defer></script>${preview ? '<meta name="robots" content="noindex">' : ''}</head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="header-inner container"><a class="brand" href="./" aria-label="Mirra home"><img src="./mark.svg" alt="" width="38" height="38">mirra</a><nav class="desktop-nav" aria-label="Main">${navigation}</nav>${headerAction}<details class="mobile-menu"><summary aria-label="Navigation menu"></summary><nav aria-label="Mobile">${navigation}${headerAction}</nav></details></div></header>
<main id="main"${document ? ' class="document"' : ''}>${content}</main>
<footer class="site-footer container"><div class="footer-top"><div class="footer-brand"><a class="footer-wordmark" href="./" aria-label="Mirra home"><img src="./mark.svg" alt="" width="76" height="76">mirra</a><p>Less app. More room for connection.</p></div><nav class="footer-links" aria-label="Footer"><div><strong>Explore</strong><a href="./#product-preview">Sample conversation</a><a href="./#how-it-works">How it works</a><a href="./#download">Availability</a></div><div><strong>Here to help</strong><a href="./support.html">Support</a><a href="./delete-account.html">Delete account</a></div><div><strong>The details</strong><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a></div></nav></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Mirra</span><p>For adults 18+. AI guidance and conversation statistics are estimates. Mirra is a reflection tool, not medical or mental-health care.</p></div></footer>
</body></html>`.replaceAll('./mark.svg', `./mark.svg?v=${version}`));
}
page('index.html', 'Mirra: more real life, less app', 'Passive recording for conversations throughout your day. Start a session, let Mirra record in the background, then get a short debrief tailored to your goal.', readFileSync(join(root, 'home.html'), 'utf8')
  .replace('{{heroAction}}', heroAction)
  .replace('{{availabilityEyebrow}}', availablePlatforms ? 'Make room for connection' : 'Preparing for launch')
  .replace('{{availabilityTitle}}', iphoneAvailable && androidAvailable ? 'Now on iPhone.<br><em>And Android.</em>' : availablePlatforms ? `Now on<br><em>${availablePlatforms}.</em>` : 'Coming first<br><em>to iPhone.</em>')
  .replace('{{availabilityDescription}}', availability)
  .replace('{{availabilityAnswer}}', `${availability}${storeUrl ? ' Use the store links on this page to download.' : ''}`)
  .replace('{{downloads}}', downloads));

page('privacy.html', 'Privacy Policy: Mirra', 'What Mirra collects, how AI processing works, and how to access or delete your data.', `<p class="eyebrow">Your data, explained</p><h1>Privacy Policy</h1><p class="muted">Version September 15, 2026</p>${notice}
<h2>Who is responsible</h2><p>${config.operatorName ? esc(config.operatorName) : 'The service operator details have not yet been finalized.'} Contact: ${support}</p>
<h2>What the app processes</h2><table><thead><tr><th>Data</th><th>Purpose and storage</th></tr></thead><tbody><tr><td>Account details</td><td>Email, account ID, authentication credentials or provider identifiers, and preferences are managed by Supabase Auth and our database.</td></tr><tr><td>Recordings</td><td>Your device saves stopped recordings until a successful upload or explicit discard. Our backend temporarily decodes the audio and sends it to OpenAI for transcription; we do not keep an audio archive on our backend.</td></tr><tr><td>Transcripts and debriefs</td><td>OpenAI receives the labeled conversation and derived statistics for coaching. Debriefs and statistics are saved to your account. Transcript saving is enabled by default; you can turn it off in Voice & privacy for future conversations. Existing saved transcripts are not erased simply by switching this preference off.</td></tr><tr><td>Reflect messages</td><td>Messages, recent chat context, and relevant debriefs go to OpenAI. Saved transcript excerpts are included only when you enable that setting. Reflect chat history stays in the current app session and is not saved by Mirra as a separate chat archive.</td></tr><tr><td>Conversation goal</td><td>Your chosen goal is saved in your account and sent to OpenAI to tailor debriefs and Reflect. Each saved debrief also retains the goal used when it was processed. Goals are included in your account export and removed with their associated settings or debriefs on deletion.</td></tr><tr><td>Operational records</td><td>Hosting and authentication providers may process IP addresses, request timestamps and security logs. Monthly usage counters enforce the debrief limit. We do not intentionally log audio, transcript text or chat prompts.</td></tr></tbody></table>
<h2>AI and service providers</h2><p>OpenAI provides transcription and AI coaching. Supabase provides authentication and database storage. Requests for text coaching use <code>store=false</code>; this does not eliminate all provider retention. OpenAI's API data controls describe endpoint-specific handling and possible abuse-monitoring retention, generally up to 30 days for text requests unless an exception applies. API content is not used to train OpenAI models by default. See <a href="https://developers.openai.com/api/docs/guides/your-data">OpenAI's data controls</a> and <a href="https://supabase.com/privacy">Supabase's privacy policy</a>.</p>
<h2>This website</h2><p>GitHub Pages hosts this website and logs visitors’ IP addresses for security. The interactive sample does not request microphone access or require an account. See <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection">GitHub Pages data collection</a>.</p>
<h2>Permission and choices</h2><p>You explicitly agree before AI processing. Record only after everyone involved permits both recording and processing. Recording rules depend on location and circumstances; permission from you alone may not be sufficient. Do not upload sensitive conversations you do not have permission to share.</p><p>You can withdraw AI consent from Profile → Voice & privacy on each device. This pauses future uploads and Reflect requests from that device; it cannot recall a request already sent. Saved conversations remain available for viewing, export, or deletion. Microphone access can be revoked in device settings. The app does not use location, contact lists, advertising IDs, advertising trackers, or health-record integrations.</p>
<h2>Retention and deletion</h2><p>Saved debriefs and optional transcripts remain until you delete them or your account. A content-free deletion marker remains until account deletion to prevent delayed uploads from restoring a deleted conversation. Delete a conversation from its detail screen. Delete your account from Profile → Account actions → Delete account. This removes the Supabase account and associated debriefs, usage and preferences; local queued recordings on that device are also removed. Other devices may retain offline files until their app data is removed; uninstall Mirra or clear its local storage on devices you no longer use.</p><p>Backups and providers' security or abuse-monitoring records may persist under their configured retention and legal obligations. Deletion from the live database does not promise immediate removal from every backup. The production backup schedule and hosting retention have not yet been documented here.</p>
<h2>Your rights and safety</h2><p>Depending on where you live, you may have rights to access, correct, export, restrict or delete personal data and to complain to your local data-protection authority. Use the in-app export and deletion controls. See <a href="./delete-account.html">web deletion availability and requirements</a> for the email-based alternative. Contact information and any applicable regional representative details remain to be finalized. Mirra is intended for adults 18 and over and is not designed for children.</p><p>Data may be processed outside your country by the named providers. Production regions, applicable transfer safeguards, and the operator's legal basis for processing must be reviewed before expanding release territories. We use authenticated requests and account-scoped access controls, but no system can promise absolute security.</p><h2>Changes</h2><p>Material changes to AI processing will be described in an updated policy and the app’s privacy prompt.</p>`, true);

page('terms.html', 'Terms of Use: Mirra', 'Use Mirra responsibly, with permission and realistic expectations about AI coaching.', `<p class="eyebrow">Using Mirra responsibly</p><h1>Terms of Use</h1><p class="muted">Version September 15, 2026</p>${notice}
<h2>The service</h2><p>Mirra helps adults reflect on their conversational habits using recorded audio, estimated statistics, and AI-generated coaching. Mirra offers up to five debriefs per account per calendar month and up to 60 Reflect messages per hour. Deleting a completed debrief does not restore usage. Processing, availability, and results may vary.</p>
<h2>Permission to record and process</h2><p>You must be 18 or older and have permission from everyone involved before recording or uploading a conversation for Mirra and OpenAI to process. Comply with the laws and rules that apply to the participants and location, including workplace and professional confidentiality. Do not secretly record people, impersonate them, upload unlawful content, or use Mirra for surveillance or harassment. Stop recording if permission is withdrawn.</p>
<h2>Your content and account</h2><p>You retain rights in your content. You give the service only the permission needed to process it, provide your debriefs, and operate the features you choose. Keep your sign-in credentials private and use an account you control. Do not attempt to access another person's data, circumvent usage limits, or interfere with the service. You may export your saved data or delete your account at any time through the available controls.</p>
<h2>Understand the limits</h2><p>AI can invent details or misunderstand context. Speaker identification assumes the loudest speaker is the account holder and may be wrong. Acoustic and language measurements are estimates, not verified assessments of personality, emotions, health, relationships, honesty, or competence. Do not use them to make employment, educational, medical, legal or other consequential decisions about someone.</p><p>Mirra is not a clinician, therapist, diagnostic service, legal adviser, emergency service or substitute for professional care. It does not monitor conversations for emergencies. Seek appropriate professional or emergency help when needed.</p>
<h2>Availability and changes</h2><p>We cannot guarantee uninterrupted service or a particular outcome. Offline recordings upload only when the app is open with a working connection. Stopping and saving a recording before closing the app is necessary for recovery. Device loss, uninstalling, or clearing browser data may erase local recordings. Important changes to the service or these terms will be communicated through the app or published notices.</p>
<h2>Contact and applicable rights</h2><p>${support}</p><p>Nothing here excludes rights or remedies that cannot lawfully be excluded. The legal operator, release territories, governing-law provisions, dispute process, and any warranties or liability terms still require final review. No arbitration agreement or broad waiver is imposed by these draft terms.</p><p><a href="./privacy.html">Read the Privacy Policy</a>.</p>`, true);

page('support.html', 'Support: Mirra', 'Help with recording, sign-in, privacy, account deletion, and conversation coaching.', `<p class="eyebrow">A little help</p><h1>Here when you need a hand.</h1>${notice}<div class="faq">
<details open><summary>How do I start?</summary><p>Sign in with your username and password or a configured Google account, review the AI disclosure, and keep the microphone near you. Tap Record to start a session. Mirra records in the background while you focus on your conversation. Tap Stop when you’re done and keep Mirra open while it uploads. Mirra handles the analysis; read your short debrief when ready. Reflect chat and progress views are optional.</p></details>
<details><summary>How do I personalize suggestions?</summary><p>Tap Your focus on the recording screen or Profile → Your conversation goal. Choose making friends, confidence, listening, clarity, or speaking up for yourself; Everyday connection leaves the focus open. Your saved choice applies when a new recording is processed and when you use Reflect, including queued recordings processed later. Older debriefs keep their original goal. Changes save automatically; wait for Saving to finish. If a change fails, Mirra shows an error and reloads your saved choice.</p></details><details><summary>How do I sign in?</summary><p>Use the username and password you registered with, or continue with Google when available. Password recovery for username-only accounts is not currently available.</p></details>
<details><summary>What happens without internet?</summary><p>In the mobile app, after signing in and accepting processing, stopped recordings can be saved on your device. Wait until saving finishes before closing the app. The browser version needs an internet connection to load. Keep the app open after reconnecting to upload. The app cannot upload while force-quit. Avoid clearing app or browser data until your recordings have uploaded.</p></details>
<details><summary>Why is a recording waiting?</summary><p>Check connectivity, sign-in status, and your monthly usage. Oversized or unsupported recordings stay available to discard. Recordings and imports must fit within 25 MB and be no longer than 60 minutes. The app tells you when processing failed; it should not substitute an invented debrief.</p></details>
<details><summary>Do the charts know which speaker is me?</summary><p>No verified identity is available. Mirra estimates that the loudest speaker is you. Microphone placement, overlapping voices, noise and transcription mistakes can change results. Treat the debrief as a prompt for reflection, not a verdict.</p></details>
<details><summary>How do I delete my data?</summary><p>Open a conversation and tap Delete. For everything, open Profile → Account actions → Delete account. See <a href="./delete-account.html">web deletion availability and requirements</a> for accounts with an accessible email address. Username-only accounts use the in-app deletion control. Export first if you want a copy.</p></details>
<details><summary>Can I stop AI processing?</summary><p>Open Profile → Voice & privacy and withdraw AI consent. This pauses future recording uploads and Reflect requests on that device. You can still export or delete saved data.</p></details></div>
<h2>Contact</h2><p>${support}</p><h2>Credits</h2><p>Mirra uses the Inter and Instrument Serif typefaces under the SIL Open Font License. <a href="./fonts/inter-LICENSE.txt">Inter license</a> / <a href="./fonts/instrument-serif-LICENSE.txt">Instrument Serif license</a>. App dependency notices are available in Profile.</p><p>For non-private bug reports, use the <a href="https://github.com/jonathanj502/mirra/issues">Mirra issue tracker</a>. Describe what happened, your device and app version. Never post audio, transcripts, credentials, or another person's information there.</p>`, true);

page('delete-account.html', 'Delete your account: Mirra', 'Check web account deletion availability and requirements, or delete your account in the Mirra app.', `<p class="eyebrow">Your account, your choice</p><h1>Delete your account.</h1><p>Web deletion, when available, requires access to the email associated with your account. Username-only accounts cannot receive these sign-in links; use Profile → Account actions → Delete account in the app.</p><p>Deleting your account permanently removes your Mirra account, saved debriefs, transcripts, settings and monthly usage records. It cannot be undone. Export a copy in the app first if you want one. Locally queued recordings on other devices should be discarded there or removed by clearing the app's data.</p><p>The app also supports deletion from Profile → Account actions → Delete account.</p>
<div id="availability" class="notice">Checking availability…</div><form id="sign-in" class="form" hidden><label for="email">Email for your existing account</label><input id="email" name="email" type="email" autocomplete="email" required><button class="button" type="submit">Email a secure deletion sign-in link</button></form><section id="confirmed-account" hidden><p id="account-label"></p><button class="button" id="delete">Permanently delete my account</button></section><output id="result" aria-live="polite"></output><p class="note">Signing in does not delete anything. You must separately confirm deletion.</p><script src="./delete-account.js?v=${version}" defer></script>`, true);
writeFileSync(join(out, 'release.json'), JSON.stringify(config));
writeFileSync(join(out, '.nojekyll'), '');
writeFileSync(join(out, 'robots.txt'), `User-agent: *\n${preview ? 'Disallow: /' : 'Allow: /'}\n`);
console.log(`Built 5 pages in ${out}. Public launch approved: ${!preview}`);
